### ISSUE TITLE
Variable name autocompletion

### ISSUE THREAD

**Issue by mathieuhays** [tillkruss/Coda-WordPress-Mode#2]
Hi, 

I'm using version 1.1.1.
I love this syntax mode but I noticed that It disables the auto-completion for variables.
I switched to PHP-HTML and it was working so It seems to be something you have to enable in the syntax mode configuration. Is it possible for you to enable this features for the next release ?

Thanks

**Comment by mathieuhays** [comment]
I eventually managed to update directly from Coda, Still doesn't work.
I tried to do it manually as well (as you described above). Doesn't work either.

Coda: 2.5.1 - Mode : 1.2.1

**Comment by tillkruss** [comment]
When you open a PHP file, what mode is selected in `Toolbar -> Text -> Syntax Mode`?

**Comment by mathieuhays** [comment]
PHP-HTML-WP.

Should it be PHP-HTML ?

**Comment by mathieuhays** [comment]
Oh sorry about that. Just noticed your plugin is working with the PHP-HTML mode !
I should clean up my plugin list in Coda !

**Comment by tillkruss** [comment]
Glad it's working now ; )
